version: "3.4"

services:
  frontend:
    image: frontend:lastest
    environment:
      - RINKEBY_URL="https://rinkeby.infura.io/v3/3bc53211d94d46a683714244969e8f9b"
      - PRIVATE_KEY="1a9c43180299c4ad6e0ee8ec6e801aa4d0a9bd14f7e1516133e3e10d17522a68"
      - PUBLIC_KEY="0xa8B33af66c005C2A06B4A2e1EfbB32aeB36dD38d"
      - REACT_APP_Server_URL=http://localhost:5000
    # networks:
    #   - docker_net
    # links:
    #   - "backend-api"
    ports:
      - "8085:80"
    depends_on:
      - backend-api

  backend-api:
    image: backend:lastest
    environment:
      - SERVER_PORT=5000
    # networks:
    #   - docker_net
    expose:
      - "5000"
    ports:
      - "5000:5000"
    # extra hosts can be used for standalone SQL Server or services at the dev PC

# networks:
#   docker_net:
#     external:
#       name: docker_net
